from Utility import W,H  

TOUCH_TIME = 0.2
BASIC = H * 0.07
GRAVITY = BASIC * 21.0
FRICTION = 1.0
ELASTIN = 0.0
JUMP = BASIC * 11.05
BLOCK_SIZE = (BASIC, BASIC)
CHARACTER_SIZE = (BASIC, BASIC)
PATROL_MOVE_SPEED =  BASIC * 2.1
MAX_MOVE_SPEED = BASIC * 10.5
MOVE_ACCELERATE = BASIC * 42
IDLE_TIME = (0.5, 2.0)
PATROL_TIME = (1.0, 5.0)
CONFUSE_TIME = 10.0
ATTACK_RANGE = BASIC * 0.75
EVADE_RANGE = BASIC * 1.35
SEARCH_RANGE = BASIC * 5
BOMB_RANGE = BASIC * 3.0
BOMB_FORCE = BASIC * 20.0
BULLET_SPEED = BASIC * 10.0
MAXHP = 3
WORLD_REGION = (0, 0, W, H)
DAMAGE_ANGLE = 0.7
DAMAGE_TIME = 0.5
BOMB_TIME = 2.0
FLICKER_TIME = 0.5
FLICKER_SPEED = 3.141592 * 5.0
FLICKER_BRIGHT = 5.0

SCORE_KILL = 50
SCORE_HIT = 5

PARTICLE_HIT = "HIT"
PARTICLE_EXPLOSION = "EXPLOSION"
PARTICLE_TRAP_FIRE = "TRAP_FIRE"